# Generated by Django 5.2.3 on 2025-07-14 23:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('publisher_fps', models.FloatField()),
                ('receiver_fps', models.FloatField()),
                ('latency_ms', models.FloatField()),
                ('frame_number', models.IntegerField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='SurveillanceSettings',
        ),
    ]
