# Generated by Django 5.2.3 on 2025-07-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_streammetrics_delete_surveillancesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='streammetrics',
            name='component',
            field=models.CharField(default='publisher', max_length=50),
        ),
        migrations.AddField(
            model_name='streammetrics',
            name='timestamp_ms',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='streammetrics',
            name='frame_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='streammetrics',
            name='latency_ms',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='streammetrics',
            name='publisher_fps',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='streammetrics',
            name='receiver_fps',
            field=models.FloatField(default=0),
        ),
    ]
