# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x12\x08tutorial\"j\n\x0c\x43\x61meraStatus\x12\x13\n\x0bisConnected\x18\x01 \x01(\x08\x12\x12\n\nbrightness\x18\x02 \x01(\x05\x12\x10\n\x08\x63ontrast\x18\x03 \x01(\x05\x12\x10\n\x08\x65xposure\x18\x04 \x01(\x05\x12\r\n\x05\x66ocus\x18\x05 \x01(\x05\"7\n\x15\x43\x61meraSettingsCommand\x12\x0f\n\x07setting\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAMERASTATUS']._serialized_start=28
  _globals['_CAMERASTATUS']._serialized_end=134
  _globals['_CAMERASETTINGSCOMMAND']._serialized_start=136
  _globals['_CAMERASETTINGSCOMMAND']._serialized_end=191
# @@protoc_insertion_point(module_scope)
